### ISSUE TITLE
http://textileit.com/ leads to 404 page

### ISSUE THREAD

**Issue by mblayman** [textile/php-textile#149]
@netcarver, I wasn't sure where else to file this, but the textile organization page has http://textileit.com/ as the URL. That URL leads to a page that only gives 404 messages.

**Comment by wion** [comment]
@philwareham,

Maybe this is a closed issue?

Do you have a URL in mind for [this initiative](https://github.com/textile/textile-lang-com-website)?

**Comment by philwareham** [comment]
@wion the txstyle site was handed to me to update (which I’m doing gradually) although I’m keeping the install as Textpattern just for simplicity - it works and is good enough. We are going to host on the Digital Ocean Textpattern servers so I can use that domain name or something else. Probably keep it though to avoid link rot. Should be ready in a couple of weeks unless real work gets in the way.

**Comment by wion** [comment]
@philwareham,

Thanks for the update.

**Comment by philwareham** [comment]
Actually thinking about this further I’ll likeky get a new domain and then domain forward the txstyle.org name to it. Got one in mind that would be more suitable.

**Comment by philwareham** [comment]
The main issue of this topic (404 in organisation url) is fixed and I’ll anebd again when new site is live. So closing.

**Comment by wion** [comment]
I won't reopen the thread, but just to reiterate what I posted in the forum...

> Actually thinking about this further I’ll likeky get a new domain and then domain forward the txstyle.org name to it. Got one in mind that would be more suitable.

Depends what the scope of focus of the site is...

If scope is php-textile in general, I don't know, probably something like php-textile.net, or whatever. 

But if it's txp-textile specifically, as I presume, then the obvious direction as far as I see it is **textile.textpattern.com**. This matches the architecture the project is headed toward anyway, so makes sense to stay true across the board, and you don't have to buy an extra domain this way.

Taking the idea further, by anticipating the potential of markup testers for txp-markdown, txp-textup, whatever, you could have **filters.textpattern.com**, then provide for each one:

* filters.textpattern.com/textile
* filters.textpattern.com/textup
* etc.

Maybe a little more work on the latter tack, but greater traffic and link juice in the long run, thus more exposure to the project.

Two good factors to weight for this choice, though. First, I think people who would want to use Markdown, already know how, so that filter tester probably isn't important, in fact, and, well Textile is better anyway. ;) But, if Bloke eventually does tackle creating Textup some day, which would really make it a new Textpattern project filter, then this choice would be strong, even without Markdown in the picture. Conversely, if he doesn't ever want to, then the choice is easily made for textile.textpattern.com

**Comment by philwareham** [comment]
@wion from my understanding it'd be a site to show the syntax and how to use it, regardless of underlying language (although, yes, it runs txp-textile/php-textile as its engine).

Sure, if I was building a new site from scratch I'd maybe use a different web page generator (indeed, I used Jekyll/GitHub Pages for the Textpattern documentation site, so pages can be hosted, edited and collaborated on directly within GitHub) but I haven't got much time to spare not this and the site works well for what it is intended. Besides, since Jekyll has dropped redcloth and GitHub Pages doesn't allow you to run your own Ruby gems (although we could use a JS solution), it would be a disservice to Textile IMO to have its site running Markdown pages throughout.

I have a general 'textile-...' domain in mind that envelopes the project as a whole.
