### ISSUE TITLE
Restricted mode throws away the styling

### ISSUE THREAD

**Issue by lauri-elevant** [textile/php-textile#174]
It appears that the `parseAttribsToArray` method prepares the `$style` array but will throw it away if restricted mode is enabled (as it is in our use case). Apart from the inefficiency of this, I can see that at least some of the stylings are perfectly safe to apply even in restricted mode. I am a bit skeptical about the `/\{([^}]*)\}/` match since `cleanAttribs` does not claim to offer full sanitation. But others seem safe to apply..

It is my understanding that restricted mode is not meant to limit functionality per se, but avoid applying potentially unsafe transformations on user input. Would it make sense to enable some of the styling options in restricted mode to make it more functional without any apparent (to me at least) cost to safety?

**Comment by gocom** [comment]
It's both 'feature' and security limited, as the restricted mode must prevent both programmatic and visual issues. For instance, in restricted mode the user must not be able to add paddings etc. Otherwise the untrusted user can spam your website with padding, and break the content flow.

> It appears that the parseAttribsToArray method prepares the $style array but will throw it away if restricted mode is enabled (as it is in our use case). Apart from the inefficiency of this, I can see that at least some [...] about the `/\{([^}]*)\}/`

It's not there to sanitize anything, but it's needed. In restricted mode it's used to strip the CSS styles notation, so that the other regexes can match their thing. Remove it, and rest of the rules start to do strange things.
