### ISSUE TITLE
Fix usage of $style in Parser::parseAttribsToArray

### ISSUE THREAD

**Issue by jwulfgit** [textile/php-textile#175]
In a PHP7-environment, I got the Error

> [] operator not supported for strings

whenever Parser::parseAttribsToArray() tried to write into its local variable $style. I assume this is because $style is initialized as a string but then used as an array (and later as string again).

I suggest fixing this by initializing $style as an array in the first place.

**Comment by ivantcholakov** [comment]
```
An uncaught Exception was encountered
Type: Error
Message: [] operator not supported for strings
Filename: ......../vendor/netcarver/textile/src/Netcarver/Textile/Parser.php
Line Number: 2062
```
v3.6.0
PHP 7.1.5

**Comment by IngoWinter** [comment]
This: `h1=. Centered headline` produces a fatal error since PHP 7.1.0:
[Applying the empty index operator to a string (e.g. $str[] = $x) throws a fatal error instead of converting silently to array. ](http://php.net/manual/de/migration71.incompatible.php)
Please merge the above PR or change the initialization of `$style` [here](https://github.com/textile/php-textile/blob/master/src/Netcarver/Textile/Parser.php#L2032) to `array()`. I'm monkeypatching that line since 6 months - and I'm for sure not the only one. Thank you :)

**Comment by netcarver** [comment]
This should be fixed in the master branch. The travis test failure shown next to the commit sha1 above was due to the need to drop the PHP5.3 tests from the travis-ci config file. Please re-open if the error persists for you.

**Comment by stijnstijn** [comment]
I still get this error with version 3.6.0 on PHP 7.2.6. I've narrowed it down to the following bit of input:

    $input = "%{font-size: 3;}foo bar%";

Stack trace:

    #0 vendor\netcarver\textile\src\Netcarver\Textile\Parser.php(3108): Netcarver\Textile\Parser->parseAttribsToArray('{font-size: 3;}')
    #1 [internal function]: Netcarver\Textile\Parser->fSpan(Array)
    #2 vendor\netcarver\textile\src\Netcarver\Textile\Parser.php(3089): preg_replace_callback('/\n             ...', Array, '%{font-size: 3;...')
    #3 vendor\netcarver\textile\src\Netcarver\Textile\Parser.php(3042): Netcarver\Textile\Parser->spans('%{font-size: 3;...')
    #4 vendor\netcarver\textile\src\Netcarver\Textile\Parser.php(2928): Netcarver\Textile\Parser->graf('%{font-size: 3;...')
    #5 vendor\netcarver\textile\src\Netcarver\Textile\Parser.php(2791): Netcarver\Textile\Parser->fBlock(Array)
    #6 vendor\netcarver\textile\src\Netcarver\Textile\Parser.php(1590): Netcarver\Textile\Parser->blocks('%{font-size: 3;...')
