### ISSUE TITLE
Sequence of alignment with class

### ISSUE THREAD

**Issue by vladas-palubinskas** [textile/php-textile#189]
### Prerequisites

* [x] Are you running the latest version of PHP-Textile?
* [ ] `$ composer update`?

### Problematic Textile markup

```
p(myclass)>. Some text
```

### Expected output

```html
<p class="myclass" style="text-align: right">Some text</p>
```

### Actual output

```html
<p>p(myclass)>. Some text</p>
```

### Used PHP code

```php
No <txp:php> in article nor in forms
```

#### Additional information

PHP-Textile version: 3.7
PHP version: 7.0

I cannot upgrade to Textile v3.7 with Textpattern v4.72 because of breaking many older articles with paragraphs, marked in global class first, and then aligned inline by Textile.

Tests on [Textile-lang.com](https://textile-lang.com/doc/text-alignment) give the same broken output.

**Comment by bloatware** [comment]
`p>(myclass). Some text` seems to work, fwiw.

**Comment by vladas-palubinskas** [comment]
Yes, I mean the sequence only. And the same brake with <, <>, and = alignment, too.

**Comment by gocom** [comment]
PHP-Textile 3.6.0 and 3.5.5 would generate the same. The alignment indicator has been required to be at the beginning, right after the tag name, since version 3.5.5.

Before that it was indicated that it was best to be the used in the beginning (the first position was reserved for the alignment), but it could also been used anywhere in the tag declaration; also multiple times, likely also within attributes and in the content of some tags.

**Comment by vladas-palubinskas** [comment]
I don't remember which version of Textile has become sequence-sensitive. Not a big problem for new writings, yet many older articles are broken now. The former sequence was quite logical for me: global settings first, and local ones last — p(class){style}>. Could I close this issue?
