### ISSUE TITLE
Error with closing quotation mark in French

### ISSUE THREAD

**Issue by cara-tm** [textile/php-textile#214]
### Prerequisites

* [x] Are you running the latest version of PHP-Textile?
* [ ] `$ composer update`?

### Problematic Textile markup

In French, the ellipses (suspension points) after a closing quotation mark need a space (not required in French) otherwise the quotation mark is transformed into an open one (this problem may be occurring with a period: to be confirmed).

### Expected output

```html
 «les rouges Ceylans»…
```

### Actual output

```html
 «les rouges Ceylans«…
```

### Used PHP code

```php
{Please write here}
```

#### Additional information

PHP-Textile version: 3.7.6
PHP version: 7.4.15

**Comment by gocom** [comment]
What is the input Textile  markup that generates the output so that we could try to create test case for this and try to reproduce it?

Also having the used configured quote symbols would help. Altho, I can go hunting them from Textpattern CMS' language packages and source code.

PHP-Textile itself doesn't have understanding of French or other languages. Systems such as Textpattern CMS, provide it different quote symbols which it then uses as quote replacements.

**Comment by cara-tm** [comment]
You are absolutely right (my fault): in Textpattern CMS there are no typographical problems. Double quotes are parsed into correct quotation marks (based on the current language). 

Thank you. Please, close this issue.
