### ISSUE TITLE
Paragraph must end before list

### ISSUE THREAD

**Issue by eliph** [textile/php-textile#22]
Consider this unordered list:

```
*Colors*
* Red
* Green
* Blue
```

It is rendered as:

```
<p><strong>Colors</strong>
<ul>
  <li>Red</li>
  <li>Green</li>
  <li>Blue</li>
</ul></p>
```

but should be:

```
<p><strong>Colors</strong></p>
<ul>
  <li>Red</li>
  <li>Green</li>
  <li>Blue</li>
</ul>
```

To avoid this, you could add a new line before the list, of course. But shouldn't textile yield valid code in every instance?

**Comment by ikirudennis** [comment]
The issue here is about perceived ambiguity in the textile syntax.  @eliph's first post in this thread wonders if the output is correct.  To my mind, the output _is_ correct.  There's nothing wrong with a `<ul>` being inside a `<p>`; it's valid HTML.  If a separated paragraph and list is desired, then the input should specify that, no?
